services:
  # 풀스택 서비스 (백엔드 + 프론트엔드)
  - type: web
    name: cafe-fullstack
    env: python
    plan: free
    region: oregon
    buildCommand: |
      # Node.js 설치
      curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      sudo apt-get install -y nodejs
      
      # 프론트엔드 빌드
      cd cafe-recommend/frontend
      npm ci
      npm run build
      
      # 빌드된 정적 파일을 백엔드 static 폴더로 복사
      mkdir -p ../backend/static/frontend
      cp -r out/* ../backend/static/frontend/
      
      # 백엔드 의존성 설치
      cd ../backend
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: |
      cd cafe-recommend/backend
      python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1 --timeout-keep-alive 30
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: SECRET_KEY
        value: cc0b57a5b7a4f9f1a6e9d8c7e5a0a3b8a2f0c7d8e1a9b6c5d4e3f2a1b0c9d8e7
      - key: DATABASE_URL
        value: sqlite:///./cafe_app.db
      - key: NEXT_PUBLIC_FRONTEND_URL
        value: https://cafe-fullstack-q9ri.onrender.com
      - key: BACKEND_CORS_ORIGINS
        value: '["https://cafe-fullstack-q9ri.onrender.com", "http://localhost:3000"]'
      - key: FIRST_SUPERUSER
        value: admin@test.com
      - key: FIRST_SUPERUSER_PASSWORD
        value: admin1234
      - key: OPENAI_API_KEY
        value: your-openai-api-key-here
      - key: OPENAI_MODEL
        value: gpt-4-turbo-preview
      - key: KAKAO_SECRET_KEY_DEV
        value: DEV880C0DBCE207B93C70140634D8226E62DFBD5
      - key: KAKAO_PAY_API_URL
        value: https://open-api.kakaopay.com
      - key: KAKAO_CID
        value: TC0ONETIME
      - key: NAVER_PAY_API_URL
        value: https://dev-pub.apis.naver.com
      - key: NAVER_PAY_PARTNER_ID
        value: np_pbyrr410908
      - key: NAVER_PAY_CLIENT_ID
        value: HN3GGCMDdTgGUfl0kFCo
      - key: NAVER_PAY_CLIENT_SECRET
        value: ftZjkkRNMR
      - key: NAVER_PAY_CHAIN_ID
        value: c1l0UTFCMlNwNjY 