services:
  # 백엔드 서비스 (FastAPI)
  - type: web
    name: cafe-backend
    env: python
    plan: free
    region: oregon
    buildCommand: |-
      echo "=== 백엔드 빌드 시작 ==="
      cd cafe-recommend/backend
      
      # Python 의존성 설치
      echo "=== Python 의존성 설치 중 ==="
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      
      echo "=== 백엔드 빌드 완료 ==="
    startCommand: cd cafe-recommend/backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1 --timeout-keep-alive 30
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: SECRET_KEY
        value: cc0b57a5b7a4f9f1a6e9d8c7e5a0a3b8a2f0c7d8e1a9b6c5d4e3f2a1b0c9d8e7
      - key: DATABASE_URL
        value: sqlite:///./cafe_app.db
      - key: BACKEND_CORS_ORIGINS
        value: '["https://cafe-frontend.onrender.com", "http://localhost:3000"]'
      - key: FIRST_SUPERUSER
        value: admin@test.com
      - key: FIRST_SUPERUSER_PASSWORD
        value: admin1234
      - key: OPENAI_API_KEY
        value: your-openai-api-key-here
      - key: OPENAI_MODEL
        value: gpt-4-turbo-preview
      - key: KAKAO_SECRET_KEY_DEV
        value: DEV880C0DBCE207B93C70140634D8226E62DFBD5
      - key: KAKAO_PAY_API_URL
        value: https://open-api.kakaopay.com
      - key: KAKAO_CID
        value: TC0ONETIME
      - key: NAVER_PAY_API_URL
        value: https://dev-pub.apis.naver.com
      - key: NAVER_PAY_PARTNER_ID
        value: np_pbyrr410908
      - key: NAVER_PAY_CLIENT_ID
        value: HN3GGCMDdTgGUfl0kFCo
      - key: NAVER_PAY_CLIENT_SECRET
        value: ftZjkkRNMR
      - key: NAVER_PAY_CHAIN_ID
        value: c1l0UTFCMlNwNjY

  # 프론트엔드 서비스 (Next.js)
  - type: web
    name: cafe-frontend
    env: node
    plan: free
    region: oregon
    buildCommand: |-
      echo "=== 프론트엔드 빌드 시작 ==="
      cd cafe-recommend/frontend
      
      # package.json 확인
      ls -la
      cat package.json
      
      # npm 의존성 설치
      npm ci
      
      # Next.js 빌드
      npm run build
      
      # 빌드 결과 확인
      echo "=== 빌드 결과 확인 ==="
      ls -la .next/
      
      echo "=== 프론트엔드 빌드 완료 ==="
    startCommand: cd cafe-recommend/frontend && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NEXT_PUBLIC_API_URL
        value: https://cafe-backend.onrender.com
      - key: NEXT_PUBLIC_FRONTEND_URL
        value: https://cafe-frontend.onrender.com
      - key: NEXT_PUBLIC_AITOPIA_URL
        value: https://extensions.aitopia.ai
      - key: NEXT_PUBLIC_OPENAI_API_URL
        value: https://api.openai.com 