"""Replace numeric taste fields with text descriptions

Revision ID: 8cdb4c273f47
Revises: 48cad9a52d68
Create Date: 2025-03-31 14:14:03.052483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cdb4c273f47'
down_revision: Union[str, None] = '48cad9a52d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('taste_profile', sa.Text(), nullable=True))
    op.add_column('menus', sa.Column('temperature_desc', sa.String(), nullable=True))
    op.drop_column('menus', 'bitterness')
    op.drop_column('menus', 'temperature')
    op.drop_column('menus', 'sourness')
    op.drop_column('menus', 'sweetness')
    op.add_column('orders', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('items', sa.JSON(), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('orders', 'items')
    op.drop_column('orders', 'payment_method')
    op.add_column('menus', sa.Column('sweetness', sa.FLOAT(), nullable=True))
    op.add_column('menus', sa.Column('sourness', sa.FLOAT(), nullable=True))
    op.add_column('menus', sa.Column('temperature', sa.VARCHAR(), nullable=True))
    op.add_column('menus', sa.Column('bitterness', sa.FLOAT(), nullable=True))
    op.drop_column('menus', 'temperature_desc')
    op.drop_column('menus', 'taste_profile')
    # ### end Alembic commands ###
