"""Add payment_settings table

Revision ID: 88b4cf9e1d2a
Revises: 1c9d46530ab7
Create Date: 2024-06-02 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '88b4cf9e1d2a'
down_revision: Union[str, None] = 'd9436a89dc32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('client_secret', sa.String(), nullable=True),
    sa.Column('additional_settings', sqlite.JSON(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_settings_id'), 'payment_settings', ['id'], unique=False)
    op.create_index(op.f('ix_payment_settings_provider'), 'payment_settings', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_settings_provider'), table_name='payment_settings')
    op.drop_index(op.f('ix_payment_settings_id'), table_name='payment_settings')
    op.drop_table('payment_settings')
    # ### end Alembic commands ### 