"""Add rating and properties columns to menus

Revision ID: f2c2dff7eeab
Revises: 92a5d3ee31ec
Create Date: 2025-03-30 20:07:10.909201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2c2dff7eeab'
down_revision: Union[str, None] = '92a5d3ee31ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('menus', sa.Column('properties', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', 'properties')
    op.drop_column('menus', 'rating')
    # ### end Alembic commands ###
